spring:
  rabbitmq:
    host: rabbitmq
    username: user
    password: password
    port: 5672
    exchange: mstc.exchange
    routingKey: mstc.routingKey
    queue:
      response: mstc.queue.response
      work: mstc.queue.work
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
minio:
  host: localhost
  port: 9000
  user: mstc
  password: fishstick
  bucket:

logging:
  level:
    org:
      springframework: WARN

    mstc: DEBUG