spring:
  rabbitmq:
    host: ${WORK_QUEUE_HOST}
    port: ${WORK_QUEUE_PORT}
    username: ${WORK_QUEUE_USER}
    password: ${WORK_QUEUE_PASS}
    template:
      mandatory: true

logging:
  level:
    org:
      springframework:
        amqp: DEBUG

    mstc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"