apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
  ports:
    - name: {{ .Values.app.ports.name }}
      protocol: TCP
      port: {{ .Values.app.ports.port }}
      targetPort: {{ .Values.app.ports.targetPort }}
    - name: {{ .Values.app.admin.name }}
      protocol: TCP
      port: {{ .Values.app.admin.port }}
      targetPort: {{ .Values.app.admin.targetPort }}
