kind: Namespace
apiVersion: v1
metadata:
  name: mstc-dev
  labels:
    name: mstc-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: mstc-dev
data:
  MINIO_USER: user
  MINIO_PASS: password
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mstc
  namespace: mstc-dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mstc
  namespace: mstc-dev
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - namespaces
      - services
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mstc
  namespace: mstc-dev
subjects:
  - kind: ServiceAccount
    name: mstc
    namespace: mstc-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mstc